export const FETCH_SUGGESTED_USERS_START = "FETCH_SUGGESTED_USERS_START";
export const FETCH_SUGGESTED_USERS_SUCCESS = "FETCH_SUGGESTED_USERS_SUCCESS";
export const FETCH_SUGGESTED_USERS_FAIL = "FETCH_SUGGESTED_USERS_FAIL";
export const WEB_INFO_FOOTER_SIDEBAR = "WEB_INFO_FOOTER_SIDEBAR";
